### ISSUE TITLE
Doesn't work with "@typescript-eslint/parser": "6.1.0"

### ISSUE THREAD

**Issue by IMalaniak** [mdbetancourt/eslint-plugin-neverthrow#14]
After a major update of @typescript-eslint/parser there are some problems parsing types from neverthrow. While linting I've got the following:

```
ESLint: 8.45.0

Error: Error while loading rule 'neverthrow/must-use-result': types not available, maybe you need set the parser to @typescript-eslint/parser
Occurred while linting /packages/backend/src/app.module.ts
    at Object.create (/node_modules/eslint-plugin-neverthrow/dist/src/rules/must-use-result.js:158:19)
    at createRuleListeners (/node_modules/eslint/lib/linter/linter.js:870:21)
    at /node_modules/eslint/lib/linter/linter.js:1040:110
    at Array.forEach (<anonymous>)
    at runRules (/node_modules/eslint/lib/linter/linter.js:977:34)
    at Linter._verifyWithoutProcessors (/node_modules/eslint/lib/linter/linter.js:1330:31)
    at Linter._verifyWithConfigArray (/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/node_modules/eslint/lib/linter/linter.js:1412:65)
    at Linter.verifyAndFix (/node_modules/eslint/lib/linter/linter.js:1967:29)
    at verifyText (/node_modules/eslint/lib/cli-engine/cli-engine.js:254:48)
npm ERR! Lifecycle script `lint` failed with error: 
npm ERR! Error: command failed 
```

Setup:

- NPM workspace

```
    "@typescript-eslint/eslint-plugin": "6.1.0",
    "@typescript-eslint/parser": "6.1.0",
    "eslint": "8.45.0",
    "eslint-plugin-neverthrow": "1.1.4"
```

**Comment by LucasDemea** [comment]
I faced the same issue. In my case, I was missing the `project: ['./tsconfig.json']` option, in my eslint config.

Here is the related part in eslint config :
```js
parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaVersion: 2022,
    project: ['./tsconfig.json'],
    tsconfigRootDir: __dirname,
}
```

**Comment by flavour-of-qualia** [comment]
@tmountain have you figured out how to use it? I believe that the newest version of eslint is not supported by this plugin

**Comment by ctsstc** [comment]
I'm assuming #19 is a duplicate.

I fought a hard battle and ended up at the same spot as you @tmountain 

I'd love to utilize this eslint plugin, but it seems that there hasn't been much movement in the last 4 years for this, so I wonder if there's any active development still occuring? Someone might have to fork this.

**Comment by mdbetancourt** [comment]
Hi @ctsstc this plug-in is not maintained anymore but any pull request is welcomed

**Comment by tmountain** [comment]
@ctsstc - I found a solution. I will share it tomorrow.

**Comment by tmountain** [comment]
@ctsstc https://github.com/tmountain/eslint-plugin-neverthrow-must-use

**Comment by FunctionDJ** [comment]
I found https://github.com/ninoseki/eslint-plugin-neverthrow
As of writing it's not popular so I checked the package contents, if the NPM package truly comes from the repository (bidirectional references), and gave the code a quick glance and ran it through some scanners. The author also has a very legitimate looking set of repositories and commit history (those can be faked, but many pieces make the puzzle). Personally, I trust this package right now, so I'm installing it and seeing if it works, maybe file issues if I run into any.
